config/routes.rb
Rails.application.routes.draw do
  resource :account

  get 'dashboard', to: 'dashboard#index'
  default_url_options host: ENV['APP_DOMAIN'], protocol: 'https'

  post 'twilio/route'
  post 'twilio/status'
  post 'twilio/outbound'
  post 'twilio/outbound_status'
  post 'twilio/recording'
  post 'twilio/transcribe'
  post 'twilio/sms'

  devise_for :users
  post 'message/:network_id/reply', to: 'messages#reply', as: 'message_reply'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'robots#health_check'
  get 'robots/health_check'
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :users
  has_many :numbers
  has_many :calls
  has_many :messages

  after_commit(on: :create) { ImportJob.perform_later(id) }

  def whitelisted?(from)
    whitelist_disabled? ||
      whitelist&.include?(from)
  end

  def whitelist_disabled?
    forward_all_until &&
      forward_all_until > Time.current
  end

  def twilio_api
    twilio_client.api.account
  end

  def twilio_client
    @client ||= Twilio::REST::Client.new(twilio_sid, twilio_token)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :account
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :account

  def contact_number
    outbound? ? to : from
  end

  # you can 'reply' to any message, so to/from decision is awkward
  def reply(new_content)
    child = self.class.new(
      account: account,
      from: outbound? ? from : to,
      to: outbound? ? to : from,
      outbound: true,
      content: new_content
    )
    child.send!
    child.save!
    child
  end

  def send!
    response = account.twilio_api.messages.create(
      body: content,
      from: from,
      to: to
    )
    self.network_id = response.sid
  end
end

app/models/number.rb
class Number < ApplicationRecord
  belongs_to :account
  has_many :users, through: :account
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :account, optional: true
  has_many :numbers, through: :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @account = current_user.account ||= Account.new
  end

  def update
    current_user.account ||= current_user.build_account
    current_user.account.assign_attributes(account_params)
    Account.transaction do
      current_user.account.save!
      current_user.save!
    end
    redirect_to edit_account_path, flash: { notice: 'Success!' }
  end

  private

  def account_params
    params.require(:account).permit(
      :twilio_token, :twilio_sid,
      whitelist: []
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_set_up

  def index
    @calls = current_user.account.calls.order(created_at: :desc).take(5)
    @messages = current_user.account.messages.order(created_at: :desc).take(20)
  end

  private

  def ensure_set_up
    redirect_to(edit_account_path) unless current_user.account
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def reply
    @message = Message.find_by!(network_id: params.require(:network_id))
    new_message = @message.reply(params.require(:content))
    redirect_to request.referrer
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def health_check
    render json: { healthy: true }
  end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  skip_forgery_protection

  def route
    if params[:CallStatus] == 'ringing'
      handle_new_call
    elsif %w[no-answer busy failed].include?(params[:DialCallStatus])
      record_voicemail
    end
    render xml: xml_response
  end

  def status
    finalize_call if params.key?(:CallDuration)
    head 201
  end

  def outbound
    return caller_id_feedback unless outbound_caller_id
    xml.Dial(
      stripped(:To),
      callerId: outbound_caller_id,
      answerOnBridge: true
    )
    render xml: xml_response
  end

  def outbound_status
    finalize_call(outbound: true) if params.key?(:CallDuration)
    head 201
  end

  def recording
    head 201
  end

  def transcribe
    head 201
  end

  def sms
    account.messages.where(network_id: params[:MessageSid]).first_or_create!(
      to: stripped(:To),
      from: stripped(:From),
      content: params[:Body]
    )
    head 201
  end

  private

  def stripped(param_key)
    @stripped ||= {}
    @stripped[param_key] ||= strip(params[param_key])
  end

  def strip(param)
    return nil unless param
    param = param.split(/[:@]/)[1] if param.start_with?('sip:')
    param.gsub(/\D/, '')
  end

  def handle_new_call
    if account.whitelisted?(stripped(:From))
      dial_sip_user
    else
      xml.Reject
    end
  end

  # really the only thing unique here is that we'll have duration set
  def finalize_call(outbound: nil)
    account.calls.where(network_id: params[:CallSid]).first_or_create!(
      to: stripped(:To),
      from: stripped(:From),
      outbound: outbound,
      duration: params[:CallDuration]
    )
  end

  def dial_sip_user
    xml.Dial(answerOnBridge: true, action: 'route') do
      xml.Sip(sip_user_address)
    end
  end

  def record_voicemail
    xml.Say('Leave a voicemail after the tone.')
    xml.Record(
      maxLength: 60,
      transcribeCallback: 'transcribe',
      recordingStatusCallback: 'recording'
    )
  end

  def sip_user_address
    sip_user = inbound_user.email.split('@').first
    "sip:#{sip_user}@#{ENV['TWILIO_SIP_DOMAIN']}"
  end

  def xml_response
    wrapper = Builder::XmlMarkup.new
    wrapper.instruct!
    wrapper.Response do
      wrapper << xml.target!
    end
    wrapper.target!
  end

  def outbound_user
    return @outbound_user if defined?(@outbound_user)
    from_user = params[:From].split(/[:@]/)[1]
    @outbound_user = account.users
      .where("email LIKE ?", "#{from_user}%").first!
  end

  def outbound_caller_id
    outbound_user.caller_id ||
      account.numbers.find_by(user_id: outbound_user.id)&.number
  end

  def caller_id_feedback
    xml.Say("You must set your caller ID before dialing outbound. Goodbye.")
    xml.Hangup
    render xml: xml_response
  end

  def inbound_number
    @inbound_number ||= Number.find_by!(number: stripped(:To))
  end

  def inbound_user
    @user ||= inbound_number.user
  end

  def account
    @account ||= Account.find_by(twilio_sid: params.require(:AccountSid))
  end

  def xml
    @xml ||= Builder::XmlMarkup.new
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def twilio_creds_valid?
    return @twilio_creds_valid if defined?(@twilio_creds_valid)
    @twilio_creds_valid = twiml_apps_returned?
  end

  def twiml_apps_returned?
    twiml_apps
    true
  rescue
    false
  end

  def twiml_apps
    @account.twilio_api.applications.list
  end

  def numbers
    @account.twilio_api.incoming_phone_numbers.list
  end

  def sip_addresses
    @account.twilio_api.sip.domains.list.flat_map do |domain|
      domain.auth.registrations.credential_list_mappings.list.flat_map do |clm|
        credential_mapping[clm.sid].credentials.list.map do |credential|
          "#{credential.username}@#{domain.domain_name}"
        end
      end
    end
  end

  def credential_mapping
    @cm ||= @account.twilio_api.sip.credential_lists
      .list.each_with_object({}) do |cred, obj|
        obj[cred.sid] = cred
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/accounts/_twilio_overview.html.erb
<h3>Twilio Numbers</h3>
<ul>
  <% numbers.each do |number| %>
    <li>
      <%= number.phone_number %>
      <%= number.voice_application_sid %>
    </li>
  <% end %>
</ul>

<h3>TwiML Apps</h3>
<% twiml_apps.each do |app| %>
  <ul>
    <li>Name: <%= app.friendly_name %></li>
    <li>Sid: <%= app.sid %></li>
    <li>Voice: <%= app.voice_url %></li>
    <li>SMS: <%= app.sms_url %></li>
  </ul>
<% end %>

<h3>SIP Users</h3>
<ul>
<% sip_addresses.each do |address| %>
  <li><%= address %></li>
<% end %>
</ul>

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

<%= form_for @account, url: account_path, method: :put do |f| %>
  <%= f.label :twilio_sid %> <%= f.text_field :twilio_sid %>
  <%= f.label :twilio_token %> <%= f.text_field :twilio_token %>

  <h3>Whitelist:</h3>
  <input-list
    input-name="account[whitelist][]"
    <% @account.whitelist&.each_with_index do |number, i| %>
      <%= "list-item-#{i}=#{number}" %>
    <% end %>
    >
  </input-list>
  <%= f.submit %>
<% end %>

<%= render partial: 'twilio_overview' if twilio_creds_valid? %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>

<h2>Messages</h2>
<ul>
  <% @messages.group_by(&:contact_number).each do |from, messages| %>
    <li>
      <%= from %>
      <%= form_tag(message_reply_path(messages.last.network_id), style: 'display: inline;') do %>
        <%= text_field_tag :content, nil, required: true, placeholder: 'text message' %>
        <%= button_tag('send text', type: :submit) %>
      <% end %>
      <ul>
        <% messages.each do |message| %>
          <li>
            <%= (message.outbound? ? '&#128228;' : '&#128229;').html_safe %>
            <%= message.content %>
            &mdash;
            <em><%= time_ago_in_words message.created_at %> ago</em>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<h2>Calls</h2>
<ul>
  <% @calls.each do |call| %>
    <li>
      created: <%= call.created_at %><br/>
      <% if call.outbound? %>
      to: <%= call.to %><br/>
      <% else %>
      from: <%= call.from %><br/>
      <% end %>
      duration: <%= call.duration %><br/>
      direction: <%= call.outbound ? 'outbound' : 'inbound' %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calldron</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>